### ISSUE TITLE
Pdu Logger doesnt start

### ISSUE THREAD

**Issue by karfam** [harlan3/aquarius-dis-pdu#1]
Hello
PDU player and generator work justs fine.

PDU logger doesn't seem to open. is there any gui or it just records if it finds a DIS stream?

**Comment by karfam** [comment]
I found that its console based but have trouble binding the logger.


![image](https://user-images.githubusercontent.com/15799659/197501159-0eabc78f-3413-49c7-96fd-199a7e1d7055.png)

**Comment by harlan3** [comment]
Based on the error "Address already in use", you have another application bound to port 3000. This could be another DIS application or another instance of the pdu_logger. If you need to bind multiple applications to the same port, check out a separate application that I developed: https://github.com/harlan3/udp-reflector
